2871640 views filter plugin
BurdaMagazinOrg/module-fb_instant_articles pull request #100
Opened 2017-06-20 13:22 UTC by bgbohling

2017-06-20 14:12 UTC, m4olivei requested changes

2017-06-20 14:12 UTC, m4olivei commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +  const FIA_VIEW_MODE = 'fb_instant_articles';
I'd like to find a better place for this constant, since it's used elsewhere. Perhaps `\Drupal\fb_instant_articles\Form\EntityViewDisplayForm`.

2017-06-20 14:12 UTC, m4olivei commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
>     * are called.
This method description doesn't make a lot of sense, or at least isn't adding any value. I get the sense it's been copied from somewhere. I think it's better to just change this to `{@inheritdoc}`.

2017-06-20 14:12 UTC, m4olivei commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +   * view mode.
Change to "for the **fb_instant_articles** view mode"

2017-06-20 14:12 UTC, m4olivei commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +   * This uses an unreliable method for detecting custom settings for node
As far as I know what's done here is in fact a reliable method of finding this out. I think we can nix this paragraph.

2017-06-20 14:12 UTC, m4olivei commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +    $entity_bundle_info = \Drupal::service('entity_type.bundle.info');
Use dependency injection to get this service instead.

2017-06-20 14:12 UTC, m4olivei commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +    $entity_storage = \Drupal::service('entity_type.manager')->getStorage('entity_view_display');
Same as above, use dependency injection to get this service instead.

2017-06-20 14:12 UTC, m4olivei commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +      if ($view_mode instanceof EntityInterface) {
Might make more sense here to check for an instance of `EntityViewDisplayInterface`, because that's what we're really interested in checking here.

2017-06-20 14:41 UTC, bgbohling commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +   * view mode.
✔️

2017-06-20 14:41 UTC, bgbohling commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +   * This uses an unreliable method for detecting custom settings for node
Nixed.

2017-06-20 16:04 UTC, bgbohling commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +      if ($view_mode instanceof EntityInterface) {
Sounds logical, but I'm not able to make that work.  Ended up with `node_field_data.type = ''` in the query.

2017-06-20 16:07 UTC, m4olivei commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +      if ($view_mode instanceof EntityInterface) {
That could be expected behaviour if you don't have any content types enabled for FBIA.

2017-06-20 16:12 UTC, bgbohling commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +      if ($view_mode instanceof EntityInterface) {
But I do, and with EntityInterface, the type shows up in the query.

2017-06-20 16:27 UTC, m4olivei commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +      if ($view_mode instanceof EntityInterface) {
Really? It works for me. I just stepped through in xdebug and `$view_mode` ends up being a `\Drupal\Core\Entity\Entity\EntityViewDisplay` object which is an instance of `\Drupal\Core\Entity\Display\EntityViewDisplayInterface`...

2017-06-20 16:29 UTC, bgbohling commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +      if ($view_mode instanceof EntityInterface) {
That's why I'm not a Lullabot. ;)

2017-06-20 17:56 UTC, bgbohling commented on modules/fb_instant_articles_views/src/Plugin/views/filter/ValidFacebookInstantArticles.php
> +    $entity_bundle_info = \Drupal::service('entity_type.bundle.info');
Drat.  The create()/__construct() thing isn't working here, so tried a factory like you did for DrupalClient.  What a surprise, can't get that working, either.

2017-06-21 13:40 UTC, m4olivei approved these changes

2017-06-21 13:40 UTC, m4olivei commented
@bgbohling if this all looks good to you, we can merge.

2017-06-21 14:13 UTC, merged