Issue #2915661: Make field item list normalization fallback region-aware
BurdaMagazinOrg/module-fb_instant_articles pull request #121
Opened 2017-10-12 10:33 UTC by hctom

... so transformation happens with the correct region context element

See Drupal.org issue: https://www.drupal.org/node/2915661

2017-10-16 20:38 UTC, m4olivei requested changes
This is a great addition. Just one small comment. Also, it would be great to have test coverage for this, want to take a shot at adding tests?

2017-10-16 20:38 UTC, m4olivei commented on src/Normalizer/FieldItemListNormalizer.php
> +          $context = $article;
Let's call it something other than `$context`, since that is already used as the third argument to this method. Maybe `$article_context`?

2017-10-17 06:32 UTC, hctom commented
You are definitely right, I just commited a change, where the new `$context`variable is renamed to `$transformer_context`

2017-10-26 12:57 UTC, m4olivei approved these changes

2017-10-26 12:58 UTC, merged