Rule Correction for deprecated Rules etc.
BurdaMagazinOrg/module-fb_instant_articles pull request #84
Opened 2017-03-16 15:22 UTC by twitnic

corrected old rules to newer sdk rules
(Source: htdocs/sites/all/vendor/facebook/facebook-instant-articles-sdk-php/tests/Facebook/InstantArticles/Transformer/custom-html-rules.json )

2017-03-16 15:23 UTC, twitnic commented
Now it is possible to have a Vimeo-iFrame Link in the Content.

2017-09-15 21:09 UTC, m4olivei commented
@twitnic Is there a corresponding issue in the drupal.org issue queue for this?

2017-09-15 21:29 UTC, m4olivei requested changes
There are some nice changes in here, but a couple things that don't really belong in the module, and a couple questions I had.

2017-09-15 21:29 UTC, m4olivei commented on fb_instant_articles.module
> -      'class' => 'InteractiveRule',
Why is this rule going away?

2017-09-15 21:29 UTC, m4olivei commented on fb_instant_articles.module
> +      'class' => 'ImageInsideParagraphRule',
Nice.

2017-09-15 21:29 UTC, m4olivei commented on fb_instant_articles.module
> -          'selector' => 'img',
Can we leave this and have it be `img[@alt]`?

2017-09-15 21:29 UTC, m4olivei commented on fb_instant_articles.module
> -        'image.caption' => array(
Why remove this?

2017-09-15 21:29 UTC, m4olivei commented on fb_instant_articles.module
> +      'class' => 'BlockquoteRule',
This is already present in near the top of the ruleset, shouldn't be needed.

2017-09-15 21:29 UTC, m4olivei commented on fb_instant_articles.module
> +      'selector' => 'blockquote.instagram-media',
This is a rule that you should implement in a custom module, Instagram embeds are not universal.

2017-09-15 21:29 UTC, m4olivei commented on fb_instant_articles.module
> +      'selector' => 'table',
This is a bit of a stretch, any `table`'s match `InteractiveRule`? This also feels like more of a custom rule that you implement with `hook_fb_instant_articles_transformer_rules` in your own custom module.

2017-09-18 13:01 UTC, twitnic commented
Hey @m4olivei I have only added rules from https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Parser/instant-articles-rules.json or corrected existing rules.

The Facebook Rules ...

2017-09-18 14:05 UTC, m4olivei commented
@twitnic hum, the Facebook rules don't have anything matching a `table`, also, you have to consider the rules already present and their order and better integrate them.

2021-03-26 19:31 UTC, m4olivei commented
Closing as this hasn't seen any activity in awhile. I'm no longer personally maintaining the 7.x branch anymore :grimacing: .

2021-03-26 19:31 UTC, closed without merging