Issue #2871632 port the base settings config form to Drupal 8
BurdaMagazinOrg/module-fb_instant_articles pull request #90
Opened 2017-05-02 02:23 UTC by m4olivei

Ports the base module settings for to Drupal 8.

I still need to look this over and test a bit, I did this right before bed time 🌝.

2017-05-26 14:33 UTC, deviantintegral requested changes
This is well on the way! Needs tests and some relatively minor changes.

2017-05-26 14:33 UTC, deviantintegral commented on fb_instant_articles.module
> + * No ads will automatically be inserted into Instant Articles.
Can we put these constants in a class somewhere? Same thing with the method below.

2017-05-26 14:33 UTC, deviantintegral commented on fb_instant_articles.module
>      'class' => $enable_transformer_logging ? '\Drupal\fb_instant_articles\DrupalLoggerAppender' : 'LoggerAppenderNull',
Double check, is `LogAppenderNull` supposed to be a full class name, or is it just a special keyword?

2017-05-26 14:33 UTC, deviantintegral commented on src/Form/BaseSettingsForm.php
> +      '#description' => $this->t('In order to designate the domain that will host your
I'm pretty sure this has to all be on one line for localize.drupal.org to be able to extract the string.

2017-05-26 14:33 UTC, deviantintegral commented on src/Form/BaseSettingsForm.php
> +    if (filter_var($ads_iframe_url, FILTER_VALIDATE_URL) === FALSE) {
We should probably use `\Drupal\Component\Utility\UrlHelper::isValid` here.

2017-05-26 14:33 UTC, deviantintegral commented on src/Form/BaseSettingsForm.php
> +      $form_state->setErrorByName('ads_an_placement_id', $this->t('You must specify a valid Placement ID when using the Audience Network ad type.'));
Does it help to call out what the placement ID is or where you can find it?

2017-05-26 17:19 UTC, bgbohling commented
D'oh!  Forgot to do the push after committing test code.  Tests are there now, but can probably use some tweaking.  They concentrate on verifying minimal functionality instead of complete coverage.

2017-05-30 12:22 UTC, bgbohling commented on fb_instant_articles.module
> + * No ads will automatically be inserted into Instant Articles.
@deviantintegral Is there a convention to follow for this, like class name, type, etc.?

2017-05-30 12:32 UTC, bgbohling commented on fb_instant_articles.module
>      'class' => $enable_transformer_logging ? '\Drupal\fb_instant_articles\DrupalLoggerAppender' : 'LoggerAppenderNull',
LoggerAppenders are a FB SDK thing that provides a way to forward log messages from the SDK to elsewheres, like Drupal watchdog.  So I'm going to guess that `LoggerAppenderNull` is a keyword.

2017-05-30 12:35 UTC, bgbohling commented on src/Form/BaseSettingsForm.php
> +      '#description' => $this->t('In order to designate the domain that will host your
Made it a single line.

2017-05-30 12:43 UTC, bgbohling commented on src/Form/BaseSettingsForm.php
> +    if (filter_var($ads_iframe_url, FILTER_VALIDATE_URL) === FALSE) {
OK, using that thing, then.

2017-05-30 12:49 UTC, bgbohling commented on src/Form/BaseSettingsForm.php
> +      $form_state->setErrorByName('ads_an_placement_id', $this->t('You must specify a valid Placement ID when using the Audience Network ad type.'));
It looks like this is something set up in the brand's Audience Network account for Instant Articles.  Adding the instrux from the FB developer docs to the form feedback.

2017-06-06 18:33 UTC, m4olivei commented on fb_instant_articles.module
> + * No ads will automatically be inserted into Instant Articles.
@deviantintegral we can, but at this stage of the port there isn't a good home for it yet. Let's leave it for now and come back to it. These constants will most likely see actual use in https://www.drupal.org/node/2872807. There should be a good home in the implementation there. I'd like to wait until that evolves, in the meantime, I'll mark a @ todo.

2017-06-06 18:45 UTC, m4olivei commented on fb_instant_articles.module
>      'class' => $enable_transformer_logging ? '\Drupal\fb_instant_articles\DrupalLoggerAppender' : 'LoggerAppenderNull',
It is a class name. It lives in the apache/log4php package. It's in the global namespace, and this value is used within the package, so I believe it's correct as is.

2017-06-06 19:15 UTC, m4olivei commented
Addressed all review comments. Added some extra assertions, rebased against 8.x-2.x, and cleaned up some code style.

@deviantintegral could you give this another look?

2017-06-07 14:26 UTC, bgbohling approved these changes
Looks good to me.

2017-06-08 01:06 UTC, deviantintegral commented on fb_instant_articles.module
>      'class' => $enable_transformer_logging ? '\Drupal\fb_instant_articles\DrupalLoggerAppender' : 'LoggerAppenderNull',
Boo, global namespace. Should it be prefixed with a \ then to make it clear, given that the other option is namespaced?

2017-06-08 01:08 UTC, deviantintegral approved these changes

2017-06-08 01:08 UTC, deviantintegral commented
The backslash thing is no big deal, whatever you decide this is good to merge. Thanks!

2017-06-08 13:22 UTC, merged

2017-06-08 13:22 UTC, m4olivei commented
Thanks!